### PR TITLE
Allow the start of the scheduler with no provided tasks

### PR DESCRIPTION
**Pull request by netcho**

### CODE REVIEW

**Comment by tobilg** [comment]
Hi and thanks for the PR. Can you please elaborate why the start without tasks would make sense?

**Comment by netcho** [comment]
I'm working on a framework which "polls" for tasks to schedule or stop. That being said, the framework has to be able to operate/to start even if there are no tasks to be run at the moment.

**Comment by tobilg** [comment]
I see... I'll have a look over the weekend. IMO, the PR will not enable this, because you'll also need a way to pass the tasks once the scheduler started. Or did you try this already?

**Comment by netcho** [comment]
Right now I'm just pushing tasks to pendingTasks, then the framework launches them once it receives an offer. A more elegant and non-hacky solution would be the implementation of a method to the Scheduler class

**Pull request closed without merging**
